man/mkinitcpio.8.txt, mkinitcpio
We achieve this by stripping timestamps from within the filesystem,
and by using a pipeline to strip inodes from the cpio archive.
It functions for at least the 'gzip', 'xz', 'bzip2', 'lz4' and 'cat'
compressors. The 'lzop' compressor embeds a runtime timestamp.
Motivation: https://reproducible-builds.org
Signed-off-by: Daniel Edgecumbe <git@esotericnonsense.com>
=> mkinitcpio: Produce reproducible initramfs images

mkinitcpio, shell/bash-completion, shell/zsh-completion
The hookdir option was still lacking addition to the option parser. As well, as the shell completions were lacking it.
=> Fix hookdir flag

functions
modinfo have started reporting filenames as "(builtin)" on built-in
modules. Ignore these and continue with other modules.
Fixes: https://bugs.archlinux.org/task/65564
Introduced in: https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git/commit/?id=e7e2cb61fa9f1db3429d91ef6accff549500d268
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> [functions] Ignore modinfo built-in modules

PKGBUILD, lsinitcpio, man/mkinitcpio.conf.5.txt, mkinitcpio, mkinitcpio.conf
This mainly for testing purposes until https://lkml.org/lkml/2020/7/23/1010 is merged in mainline.
Then this patch can  be safely applied
=> mkinitcpio: Add support for the zstd compressor

install/block
Filtering only by mmc pulls in media/mmc which would include modules and
firmware for dvb.
=> block: only include drivers/mmc

libalpm/hooks/60-mkinitcpio-remove.hook, libalpm/hooks/90-mkinitcpio-install.hook
With reference to similar changes in other packages (systemd, kmod, dbus) it would be good to change here as well.
Signed-off-by: Piotr Gorski <lucjan.lucjanov@gmail.com>
=> alpm-hooks should use Type = Path, not File

install/block
This allows for booting from an ISO that was copied to a pmem device, such as '/dev/pmem0'.
See also https://github.com/u-root/webboot/.
----
This is an alternative to #30.
=> install/block: include NVDIMM modules

install/fsck
Within a (build) chroot we may have root on tmpfs. There is no fsck
helper for tmpfs, so do not complain.
Signed-off-by: Christian Hesse <mail@eworm.de>
=> fsck: do not complain about missing helper for tmpfs

mkinitcpio
Background info: I was using lz4 for its speed and switched to zstd after the recent release. However `zstd -19` is very slow on my machine and I wish to override the compression level which I found is impossible and hence this patch.
Another related question, why only zstd utilize a [compression level](https://github.com/archlinux/mkinitcpio/blob/master/mkinitcpio#L215) that is not the program default (`-3`)? All others (lz4, gzip) use the default compression level from the respective programs.
EDIT: Answering the question myself, see: https://github.com/archlinux/mkinitcpio/pull/35#discussion_r460510753
=> Allow user to override default compression options

mkinitcpio
This PR removes the explicit default of -15 for zstd compression.
The reason for this proposal is, as can be seen in the plot below, that -15 is still paying significant CPU cost for barely any gain. By removing -15, zstd would, if the user didn't specify anything else, resort to level 3, which saves significant compression times while raising the filesize only by 2.5% of the original size.
Furthermore, this would make the behavior of mkinitcpio less surprising in this regard, as all other compressors are used with their default levels, only zstd has an explicit level set, potentially leading to user confusion, why zstd, known among other things for its compression speed, is slower than other compressors like lz4.
Given the data shown below and the principle of least surprise, and given …
=> Change explicit default for compression level of zstd

PKGBUILD, man/mkinitcpio.conf.5.txt, mkinitcpio, mkinitcpio.conf
Since all the Arch kernels now support zstd, switch to it by default
=> Switch to zstd by default

functions
kmod 28 supports modules compressed in zstd format so let's add the same functionality to mkinitcpio.
Signed-off-by: Piotr Gorski <lucjan.lucjanov@gmail.com>
=> Add zstd module decompression

man/mkinitcpio.8.txt, mkinitcpio, mkinitcpio.d/example.preset
Missing stuff for this pull-request.
---
Implement UEFI executable generation in mkinitcpio by utilizing UEFI
stubs provided by systemd/gummiboot.
This allows us to create a unified boot image we can boot from UEFI
with. These are practical for secure boot as we can sign initramfs,
kernel cmdline and the kernel all at once. By utilizing the
BOOT_LOADER_SPECIFICATION we can also drop new images into the correct
patch and have systemd-boot/gummiboot pick up the images.
The code does several things and does a fair amount of guessing to
figure out all the inputs needed.
We use `/etc/kernel/cmdline` to localize the kernel cmdline options we
want for the image. This is inherited from the `kernel-install` hook
system which might double as some form of standard.
We also do a dance to get the …
=> [mkinitcpio] Create UEFI executables

mkinitcpio
The short opts where the only one tested, seems like a few of the long
opts was missing from the array.
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> mkinitcpio: fixed missing _opt_long

mkinitcpio
Fixes https://github.com/archlinux/mkinitcpio/issues/62
Fixes https://bugs.archlinux.org/task/69024
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> mkinitcpio: Add umask 077 for artifacts

mkinitcpio
Sometimes it might be handy to add arguments to the preset options. For
instance if you are testing a new mkinitcpio feature with a preexisting
preset.
This patch allows us to use any arguments passed after "--" as an
extension to the preset options array.
mkinitcpio -p linux -- --uefi /efi/EFI/Linux/systemd-linux.efi --microcode /boot/intel-ucode.img
Would use "linux.preset" and append the --uefi and --microcode flags to
the preset option arrays.
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> mkinitcpio: Allow additional argument to preset options

functions
Deprectating a hook 'old-hook' and replacing it with new hook 'new-hook'
required the symlink to point to an absolute target:
/usr/lib/initcpio/install/old-hook -> /usr/lib/initcpio/install/new-hook
Let's canonicalize the path read by `readlink`, this allows to link
relative path in symbolic link:
/usr/lib/initcpio/install/old-hook -> new-hook
=> functions: canonicalize symbolic link path

functions
This function can be used for setups with systemd in initramfs (hook
`systemd`) or without (hook `udev`). To avoid code duplication move
the code here.
=> functions: move add_udev_rule() from systemd hook

functions
Naive implementation for compressed firmware-support.
Kernel versions >= 5.3 [1] are able to load xz-compressed firmware images. XZ is the only  algorithm that is supported by the kernel and since then there was no notable work done to add more.
Distributions might ship a mix of compressed and uncompressed firmware images and there is no way to know in advance whether images are compressed or not, so we have to test for one case and then fall back to the other for every single image. Most systems will require only a modest amount of firmware in the initramfs, even if the first case falls through for all images it won't hurt performance much.
This doesn't account for kernels that don't enable CONFIG_FW_LOADER_COMPRESS.
[1] http://lkml.iu.edu/hypermail/linux/kernel/1907.1/04265.html
=> functions: add support for compressed firmware

functions
All Arch Linux's officially supported kernels changed from `CONFIG_FAT_DEFAULT_IOCHARSET="iso8859-1"` to `CONFIG_FAT_DEFAULT_IOCHARSET="ascii"`:
- https://github.com/archlinux/svntogit-packages/commit/34bfe7d720658c7f0d14c61f44fb2a5516073c12
- https://github.com/archlinux/svntogit-packages/commit/c75cb9e71b52eef4de9ed706f01ddf5a05f9f738
- https://github.com/archlinux/svntogit-packages/commit/283332609549a479357d2d58adf80d12e89e345f
- https://github.com/archlinux/svntogit-packages/commit/760c402675ad74417005b9abad5f997f677c801e
Although currently Arch kernels have `CONFIG_NLS_ASCII=y`, since it's a tristate option, it's better to add it just in case.
----
I'm not sure if `add_module "nls_iso8859-1?"` should be kept to support kernels built with `CONFIG_FAT_DEFAULT_IOCHARSET="iso8859-1"` or …
=> functions: add nls_ascii to fat quirks

mkinitcpio
I just had a "fun" time recovering from a sysupdate-gone-wrong situation in which some files were corrupted and all initramfs files were gone. 
While trying to rescue the system, I re-ran mkinitcpio a couple of times but it never recreated the missing initramfs. Took me quite a while to figure out that the preset file (`/etc/mkinitcpio.d/linux.preset` in this case), was among the corrupted ones.
It was present and readable, but with a size of 0 bytes rather deserted...
mkinitcpio only checks that sourcing the preset file did not return any error, which makes perfect sense (from help):
```
Exit Status:
Returns the status of the last command executed in FILENAME; fails if
FILENAME cannot be read.
```
Long story short, this adds a warning if the `PRESET` variable is empty after the "source" …
=> Warn, if the preset file does not contain any presets

mkinitcpio
Setting uid and gid in bsdtar (step 2) gave no effect, so it's moved to step 1. Now all uids and gids are setting to zero. So created archive is user-independent.
Step 2 just adds files from archive from stdin, but doesn't set any metadata to them.
Before that if you ran mkinitcpio as non-root user, uid and gid of each file from archive were set to your non-zero uid and non-zero gid.
**This bug caused a following problem:**
If you create initramfs with non-root user and try to boot with it, you will get
```
mount: /proc: must be superuser to use mount.
mount: /sys: must be superuser to use mount.
mount: /dev: must be superuser to use mount.
mount: /run: must be superuser to use mount.
```
because all files in your initrd environment have non-zero uid and gid.
=> Fix setting uid=0 gid=0 in archive

functions, mkinitcpio
The kernel version scraper included in mkinitcpio works only on x86 kernel images.
This commit implements kernel version scraping on a generic architecture if an uncompressed image is provided.
With this commit I'm mainly targeting ALARM. However, since I wasn't able to find a static offset for the kernel version like on x86, I decided to go for a generic scraper that greps over the entire uncompressed image.
This is definitely inefficient, it takes ~300ms on my laptop with an NVMe SSD, 1.8s on my Rock64 with eMMC storage. However, it's better than nothing in my opinion, and people can still hardcode the kernel version in the preset just as before.
=> Add fallback kernel version scraper

functions
> depmod: WARNING: could not open modules.builtin.modinfo at /tmp/mkinitcpio.EftMSK/root/lib/modules/5.15.52-1-lts: No such file or directory
kmod wants modules.builtin.modinfo since v30 [1]
[1] https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git/commit/?id=0246e06340df292b5dda4bc00e24cc9ae894e881
=> Fix the warning about missing modules.builtin.modinfo

install/kms
This hook adds GPU drivers (`/drivers/char/agp/` and `/drivers/gpu/drm/`) to the initramfs for [early KMS](https://wiki.archlinux.org/title/Kernel_mode_setting#Early_KMS_start).
Copy of https://gitlab.archlinux.org/mkinitcpio/mkinitcpio-archiso/-/blob/23b9cd42417765cbd70e8cd26db2c699ef3cf01f/install/archiso_kms without the `SPDX-License-Identifier` line.
Fixes https://github.com/archlinux/mkinitcpio/issues/94.
```
Signed-off-by: nl6720 <nl6720@gmail.com>
```
@brain0, @djgera, @dvzrv, please comment with your `Signed-off-by` lines if you agree with this change and relicensing of the file.
=> install/kms: move archiso_kms from mkinitcpio-archiso

install/strip
In the same vein of the other options, we want to strip the kernel modules of their debug symbols when passing the strip hook.
=> Strip modules of debug symbols on strip hook.

install/fsck
`fsck.xfs` is a shell script that used to just "do nothing, succesfully", but since 5.15 it calls `xfs_repair` when invoked with -f, so we need it included with initcpio.
=> fsck.xfs needs xfs_repair for actual work (only with -f/forcefsck).

mkinitcpio
4th:
Remove not needed and not reproducable cache file
https://bugs.archlinux.org/task/73817
=> fix reproducibility, in case of /var/cache directory exists and is included in initramfs

functions
For kernels build upon git trees, any non-tag commit will append a '+'
char to kernel version.
This means the current fallback method will cut off the tailing '+' and
cause mkinitcpio failure for suck cases.
Signed-off-by: Qu Wenruo <wqu@suse.com>
=> functions: allow tailing `+` for custom kernel build upon git trees

install/autodetect
It is possible to get the upper/lower directories for overlay fs:
```
findmnt -n '/' | sed -e 's/ /\n/g' -e 's/,/\n/g' | sed -e '/^\(lower\|upper\)dir=/!d'
```
Since the root was switched to the overlay mount point, these mountpoints usually don't exist. I don't know a solution to detect the filesystemtypes of these "old" mountpoints, so fallback to autodetect failed.
If there is a better solution, I am happy to adapt the PR.
=> autodetect does not work for overlay fs, set autodetect to failed

mkinitcpio
This just applies the proposed fix from @Artefact2 in the linked issue.
Should we make this behaviour more configurable as it increases the space requirements, which could be a breaking change for people with full `/boot`?
fixes https://github.com/archlinux/mkinitcpio/issues/64
=> ensure consistency for the generated image

install/strip
=> Missing semicolons

install/fsck
When using OverlayFS on the root mount, the fsck hook will attempt to add the corresponding fsck binary, which doesn't exist.
-> Running build hook: [fsck]
==> ERROR: file not found: `fsck.overlay'
My `mount` output on the installation where I encountered this error:
none on / type overlay (rw,relatime,lowerdir=base/,upperdir=overlay/overlay-upper/,workdir=overlay/overlay-work/)
=> fsck: Don't add fsck binary for OverlayFS

functions, lsinitcpio
Make the fallback kver scraper test for gzip and use `zcat` for gzip compressed kernels.
This has been tested on qemu-system-riscv64 and the generated initramfs works pretty well.
=> Support gzip compressed linux kernels for RISC-V kernels

install/fsck
Check if the fsck helper of a `/` or `/usr` file system exists before adding it. This way, nonexistent fsck helper names do not need to be hardcoded.
Add the `e2fsck` binary and symlink `fsck.ext2`, `fsck.ext3` and `fsck.ext4` to it.
=> install/fsck: always use the add_fsck function to add fsck helpers

mkinitcpio
Previously this would fail:
```
==> Creating UEFI executable: /boot/EFI/Linux/arch.efi
==> ERROR: UEFI stub '' not found
```
With this change, the bundle is built fine:
```
==> Image generation successful
==> Creating UEFI executable: /boot/EFI/Linux/arch.efi
-> Using UEFI stub: /usr/lib/systemd/boot/efi/linuxaa64.efi.stub
-> Using kernel image: /lib/modules/6.1.0-rc3-asahi-1-1-ARCH/vmlinuz
-> Using cmdline file: /etc/kernel/cmdline
-> Using os-release file: /etc/os-release
==> UEFI executable generation successful
```
=> Add support for building UEFI bundles on aarch64
